12-19 12:14:00 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: テーブル "EMPLOYEE" が見つかりません
Table "EMPLOYEE" not found; SQL statement:
delete from EMPLOYEE where EMPLOYEE_ID = ? [42102-126]
12-19 12:14:00 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:00 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: テーブル "DEPARTMENT" が見つかりません
Table "DEPARTMENT" not found; SQL statement:
insert into DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NO) values (?, ?) [42102-126]
12-19 12:14:01 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:01 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: テーブル "EMPLOYEE" が見つかりません
Table "EMPLOYEE" not found; SQL statement:
select * from EMPLOYEE where EMPLOYEE_NAME like concat(?, '%') order by EMPLOYEE_ID [42102-126]
12-19 12:14:01 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:01 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: テーブル "SAL_EMP" が見つかりません
Table "SAL_EMP" not found; SQL statement:
select * from SAL_EMP order by NAME [42102-126]
12-19 12:14:01 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:01 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: テーブル "SAL_EMP" が見つかりません
Table "SAL_EMP" not found; SQL statement:
select * from SAL_EMP order by NAME [42102-126]
12-19 12:14:01 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:01 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: テーブル "SAL_EMP" が見つかりません
Table "SAL_EMP" not found; SQL statement:
select * from SAL_EMP order by NAME [42102-126]
12-19 12:14:01 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:01 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: テーブル "SAL_EMP" が見つかりません
Table "SAL_EMP" not found; SQL statement:
select * from SAL_EMP order by NAME [42102-126]
12-19 12:14:02 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:02 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: テーブル "DEPARTMENT" が見つかりません
Table "DEPARTMENT" not found; SQL statement:
select * from DEPARTMENT where DEPARTMENT_ID = ? [42102-126]
12-19 12:14:02 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:02 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: テーブル "DEPARTMENT" が見つかりません
Table "DEPARTMENT" not found; SQL statement:
select * from DEPARTMENT where DEPARTMENT_ID = ? [42102-126]
12-19 12:14:02 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:02 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: テーブル "DEPARTMENT" が見つかりません
Table "DEPARTMENT" not found; SQL statement:
select * from DEPARTMENT where DEPARTMENT_ID = ? [42102-126]
12-19 12:14:02 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:02 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: テーブル "COMP_KEY_DEPARTMENT" が見つかりません
Table "COMP_KEY_DEPARTMENT" not found; SQL statement:
select * from COMP_KEY_DEPARTMENT where DEPARTMENT_ID1 = ? and DEPARTMENT_ID2 = ? [42102-126]
12-19 12:14:02 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:02 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: テーブル "DEPARTMENT" が見つかりません
Table "DEPARTMENT" not found; SQL statement:
select * from DEPARTMENT where DEPARTMENT_ID = ? [42102-126]
12-19 12:14:02 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:02 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: テーブル "DEPARTMENT" が見つかりません
Table "DEPARTMENT" not found; SQL statement:
select * from DEPARTMENT where DEPARTMENT_ID = ? [42102-126]
12-19 12:14:02 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:02 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: テーブル "DEPARTMENT" が見つかりません
Table "DEPARTMENT" not found; SQL statement:
select * from DEPARTMENT where DEPARTMENT_ID = ? [42102-126]
12-19 12:14:02 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:02 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: テーブル "EMPLOYEE" が見つかりません
Table "EMPLOYEE" not found; SQL statement:
delete from EMPLOYEE where EMPLOYEE_ID = ? [42102-126]
12-19 12:14:02 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:03 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: テーブル "EMPLOYEE" が見つかりません
Table "EMPLOYEE" not found; SQL statement:
delete from EMPLOYEE where EMPLOYEE_ID = ? and VERSION = ? [42102-126]
12-19 12:14:03 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:03 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: テーブル "COMP_KEY_EMPLOYEE" が見つかりません
Table "COMP_KEY_EMPLOYEE" not found; SQL statement:
delete from COMP_KEY_EMPLOYEE where EMPLOYEE_ID1 = ? and EMPLOYEE_ID2 = ? and VERSION = ? [42102-126]
12-19 12:14:03 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:03 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: テーブル "EMPLOYEE" が見つかりません
Table "EMPLOYEE" not found; SQL statement:
select * from EMPLOYEE where EMPLOYEE_ID = ? [42102-126]
12-19 12:14:03 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:03 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: テーブル "EMPLOYEE" が見つかりません
Table "EMPLOYEE" not found; SQL statement:
select * from EMPLOYEE where EMPLOYEE_ID = ? [42102-126]
12-19 12:14:03 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:03 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: テーブル "EMPLOYEE" が見つかりません
Table "EMPLOYEE" not found; SQL statement:
delete from EMPLOYEE where EMPLOYEE_ID = ? [42102-126]
12-19 12:14:03 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:03 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: テーブル "EMPLOYEE" が見つかりません
Table "EMPLOYEE" not found; SQL statement:
delete from EMPLOYEE where EMPLOYEE_ID = ? and VERSION = ? [42102-126]
12-19 12:14:03 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:03 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: テーブル "COMP_KEY_EMPLOYEE" が見つかりません
Table "COMP_KEY_EMPLOYEE" not found; SQL statement:
delete from COMP_KEY_EMPLOYEE where EMPLOYEE_ID1 = ? and EMPLOYEE_ID2 = ? and VERSION = ? [42102-126]
12-19 12:14:03 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:03 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: テーブル "EMPLOYEE" が見つかりません
Table "EMPLOYEE" not found; SQL statement:
select * from EMPLOYEE where EMPLOYEE_ID = ? [42102-126]
12-19 12:14:03 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:03 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: テーブル "EMPLOYEE" が見つかりません
Table "EMPLOYEE" not found; SQL statement:
select * from EMPLOYEE where EMPLOYEE_ID = ? [42102-126]
12-19 12:14:03 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:03 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: テーブル "EMPLOYEE" が見つかりません
Table "EMPLOYEE" not found; SQL statement:
delete from EMPLOYEE where EMPLOYEE_ID = ? [42102-126]
12-19 12:14:03 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:04 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: テーブル "EMPLOYEE" が見つかりません
Table "EMPLOYEE" not found; SQL statement:
select * from EMPLOYEE order by EMPLOYEE_ID [42102-126]
12-19 12:14:04 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:05 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: テーブル "EMPLOYEE" が見つかりません
Table "EMPLOYEE" not found; SQL statement:
select * from EMPLOYEE order by EMPLOYEE_ID [42102-126]
12-19 12:14:05 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:05 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: テーブル "EMPLOYEE" が見つかりません
Table "EMPLOYEE" not found; SQL statement:
select * from EMPLOYEE order by EMPLOYEE_ID [42102-126]
12-19 12:14:05 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:05 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: テーブル "EMPLOYEE" が見つかりません
Table "EMPLOYEE" not found; SQL statement:
select * from EMPLOYEE where EMPLOYEE_ID = ? [42102-126]
12-19 12:14:05 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:05 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: テーブル "EMPLOYEE" が見つかりません
Table "EMPLOYEE" not found; SQL statement:
select * from EMPLOYEE order by EMPLOYEE_ID limit 5 offset 3 [42102-126]
12-19 12:14:05 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:05 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: 関数 "FUNC_NONE_PARAM" が見つかりません
Function "FUNC_NONE_PARAM" not found; SQL statement:
     call func_none_param()  [90022-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.command.Parser.readJavaFunction(Parser.java:1919)
	at org.h2.command.Parser.readFunction(Parser.java:1960)
	at org.h2.command.Parser.readTerm(Parser.java:2243)
	at org.h2.command.Parser.readFactor(Parser.java:1850)
	at org.h2.command.Parser.readSum(Parser.java:1837)
	at org.h2.command.Parser.readConcat(Parser.java:1810)
	at org.h2.command.Parser.readCondition(Parser.java:1681)
	at org.h2.command.Parser.readAnd(Parser.java:1661)
	at org.h2.command.Parser.readExpression(Parser.java:1653)
	at org.h2.command.Parser.parserCall(Parser.java:3588)
	at org.h2.command.Parser.parsePrepared(Parser.java:326)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.parse(Parser.java:263)
	at org.h2.command.Parser.prepareCommand(Parser.java:235)
	at org.h2.engine.Session.prepareLocal(Session.java:416)
	at org.h2.engine.Session.prepareCommand(Session.java:377)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1066)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcCallableStatement.<init>(JdbcCallableStatement.java:40)
	at org.h2.jdbc.JdbcConnection.prepareCall(JdbcConnection.java:809)
	at org.seasar.extension.dbcp.impl.ConnectionWrapperImpl.prepareCall(ConnectionWrapperImpl.java:185)
	at org.seasar.doma.it.ItConnection.prepareCall(ItConnection.java:128)
	at org.seasar.doma.internal.jdbc.util.JdbcUtil.prepareCall(JdbcUtil.java:78)
	at org.seasar.doma.internal.jdbc.command.ModuleCommand.execute(ModuleCommand.java:53)
	at org.seasar.doma.it.dao.FunctionDaoImpl.func_none_param(FunctionDaoImpl.java:78)
	at org.seasar.doma.it.auto.AutoFunctionTest.testNoParam(AutoFunctionTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.seasar.framework.unit.S2TestMethodRunner.executeMethodBody(S2TestMethodRunner.java:678)
	at org.seasar.framework.unit.S2TestMethodRunner.executeMethod(S2TestMethodRunner.java:653)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:618)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:05 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:05 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: 関数 "FUNC_SIMPLETYPE_PARAM" が見つかりません
Function "FUNC_SIMPLETYPE_PARAM" not found; SQL statement:
     call func_simpletype_param(?)  [90022-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.command.Parser.readJavaFunction(Parser.java:1919)
	at org.h2.command.Parser.readFunction(Parser.java:1960)
	at org.h2.command.Parser.readTerm(Parser.java:2243)
	at org.h2.command.Parser.readFactor(Parser.java:1850)
	at org.h2.command.Parser.readSum(Parser.java:1837)
	at org.h2.command.Parser.readConcat(Parser.java:1810)
	at org.h2.command.Parser.readCondition(Parser.java:1681)
	at org.h2.command.Parser.readAnd(Parser.java:1661)
	at org.h2.command.Parser.readExpression(Parser.java:1653)
	at org.h2.command.Parser.parserCall(Parser.java:3588)
	at org.h2.command.Parser.parsePrepared(Parser.java:326)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.parse(Parser.java:263)
	at org.h2.command.Parser.prepareCommand(Parser.java:235)
	at org.h2.engine.Session.prepareLocal(Session.java:416)
	at org.h2.engine.Session.prepareCommand(Session.java:377)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1066)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcCallableStatement.<init>(JdbcCallableStatement.java:40)
	at org.h2.jdbc.JdbcConnection.prepareCall(JdbcConnection.java:809)
	at org.seasar.extension.dbcp.impl.ConnectionWrapperImpl.prepareCall(ConnectionWrapperImpl.java:185)
	at org.seasar.doma.it.ItConnection.prepareCall(ItConnection.java:128)
	at org.seasar.doma.internal.jdbc.util.JdbcUtil.prepareCall(JdbcUtil.java:78)
	at org.seasar.doma.internal.jdbc.command.ModuleCommand.execute(ModuleCommand.java:53)
	at org.seasar.doma.it.dao.FunctionDaoImpl.func_simpletype_param(FunctionDaoImpl.java:154)
	at org.seasar.doma.it.auto.AutoFunctionTest.testOneParam(AutoFunctionTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.seasar.framework.unit.S2TestMethodRunner.executeMethodBody(S2TestMethodRunner.java:678)
	at org.seasar.framework.unit.S2TestMethodRunner.executeMethod(S2TestMethodRunner.java:653)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:618)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:05 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:05 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: 関数 "FUNC_SIMPLETYPE_TIME_PARAM" が見つかりません
Function "FUNC_SIMPLETYPE_TIME_PARAM" not found; SQL statement:
     call func_simpletype_time_param(?)  [90022-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.command.Parser.readJavaFunction(Parser.java:1919)
	at org.h2.command.Parser.readFunction(Parser.java:1960)
	at org.h2.command.Parser.readTerm(Parser.java:2243)
	at org.h2.command.Parser.readFactor(Parser.java:1850)
	at org.h2.command.Parser.readSum(Parser.java:1837)
	at org.h2.command.Parser.readConcat(Parser.java:1810)
	at org.h2.command.Parser.readCondition(Parser.java:1681)
	at org.h2.command.Parser.readAnd(Parser.java:1661)
	at org.h2.command.Parser.readExpression(Parser.java:1653)
	at org.h2.command.Parser.parserCall(Parser.java:3588)
	at org.h2.command.Parser.parsePrepared(Parser.java:326)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.parse(Parser.java:263)
	at org.h2.command.Parser.prepareCommand(Parser.java:235)
	at org.h2.engine.Session.prepareLocal(Session.java:416)
	at org.h2.engine.Session.prepareCommand(Session.java:377)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1066)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcCallableStatement.<init>(JdbcCallableStatement.java:40)
	at org.h2.jdbc.JdbcConnection.prepareCall(JdbcConnection.java:809)
	at org.seasar.extension.dbcp.impl.ConnectionWrapperImpl.prepareCall(ConnectionWrapperImpl.java:185)
	at org.seasar.doma.it.ItConnection.prepareCall(ItConnection.java:128)
	at org.seasar.doma.internal.jdbc.util.JdbcUtil.prepareCall(JdbcUtil.java:78)
	at org.seasar.doma.internal.jdbc.command.ModuleCommand.execute(ModuleCommand.java:53)
	at org.seasar.doma.it.dao.FunctionDaoImpl.func_simpletype_time_param(FunctionDaoImpl.java:173)
	at org.seasar.doma.it.auto.AutoFunctionTest.testOneParam_time(AutoFunctionTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.seasar.framework.unit.S2TestMethodRunner.executeMethodBody(S2TestMethodRunner.java:678)
	at org.seasar.framework.unit.S2TestMethodRunner.executeMethod(S2TestMethodRunner.java:653)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:618)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:05 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:05 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: 関数 "FUNC_DTO_PARAM" が見つかりません
Function "FUNC_DTO_PARAM" not found; SQL statement:
     call func_dto_param(?, ?)  [90022-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.command.Parser.readJavaFunction(Parser.java:1919)
	at org.h2.command.Parser.readFunction(Parser.java:1960)
	at org.h2.command.Parser.readTerm(Parser.java:2243)
	at org.h2.command.Parser.readFactor(Parser.java:1850)
	at org.h2.command.Parser.readSum(Parser.java:1837)
	at org.h2.command.Parser.readConcat(Parser.java:1810)
	at org.h2.command.Parser.readCondition(Parser.java:1681)
	at org.h2.command.Parser.readAnd(Parser.java:1661)
	at org.h2.command.Parser.readExpression(Parser.java:1653)
	at org.h2.command.Parser.parserCall(Parser.java:3588)
	at org.h2.command.Parser.parsePrepared(Parser.java:326)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.parse(Parser.java:263)
	at org.h2.command.Parser.prepareCommand(Parser.java:235)
	at org.h2.engine.Session.prepareLocal(Session.java:416)
	at org.h2.engine.Session.prepareCommand(Session.java:377)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1066)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcCallableStatement.<init>(JdbcCallableStatement.java:40)
	at org.h2.jdbc.JdbcConnection.prepareCall(JdbcConnection.java:809)
	at org.seasar.extension.dbcp.impl.ConnectionWrapperImpl.prepareCall(ConnectionWrapperImpl.java:185)
	at org.seasar.doma.it.ItConnection.prepareCall(ItConnection.java:128)
	at org.seasar.doma.internal.jdbc.util.JdbcUtil.prepareCall(JdbcUtil.java:78)
	at org.seasar.doma.internal.jdbc.command.ModuleCommand.execute(ModuleCommand.java:53)
	at org.seasar.doma.it.dao.FunctionDaoImpl.func_dto_param(FunctionDaoImpl.java:40)
	at org.seasar.doma.it.auto.AutoFunctionTest.testTwoParams(AutoFunctionTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.seasar.framework.unit.S2TestMethodRunner.executeMethodBody(S2TestMethodRunner.java:678)
	at org.seasar.framework.unit.S2TestMethodRunner.executeMethod(S2TestMethodRunner.java:653)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:618)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:05 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:06 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: 関数 "FUNC_DTO_TIME_PARAM" が見つかりません
Function "FUNC_DTO_TIME_PARAM" not found; SQL statement:
     call func_dto_time_param(?, ?)  [90022-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.command.Parser.readJavaFunction(Parser.java:1919)
	at org.h2.command.Parser.readFunction(Parser.java:1960)
	at org.h2.command.Parser.readTerm(Parser.java:2243)
	at org.h2.command.Parser.readFactor(Parser.java:1850)
	at org.h2.command.Parser.readSum(Parser.java:1837)
	at org.h2.command.Parser.readConcat(Parser.java:1810)
	at org.h2.command.Parser.readCondition(Parser.java:1681)
	at org.h2.command.Parser.readAnd(Parser.java:1661)
	at org.h2.command.Parser.readExpression(Parser.java:1653)
	at org.h2.command.Parser.parserCall(Parser.java:3588)
	at org.h2.command.Parser.parsePrepared(Parser.java:326)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.parse(Parser.java:263)
	at org.h2.command.Parser.prepareCommand(Parser.java:235)
	at org.h2.engine.Session.prepareLocal(Session.java:416)
	at org.h2.engine.Session.prepareCommand(Session.java:377)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1066)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcCallableStatement.<init>(JdbcCallableStatement.java:40)
	at org.h2.jdbc.JdbcConnection.prepareCall(JdbcConnection.java:809)
	at org.seasar.extension.dbcp.impl.ConnectionWrapperImpl.prepareCall(ConnectionWrapperImpl.java:185)
	at org.seasar.doma.it.ItConnection.prepareCall(ItConnection.java:128)
	at org.seasar.doma.internal.jdbc.util.JdbcUtil.prepareCall(JdbcUtil.java:78)
	at org.seasar.doma.internal.jdbc.command.ModuleCommand.execute(ModuleCommand.java:53)
	at org.seasar.doma.it.dao.FunctionDaoImpl.func_dto_time_param(FunctionDaoImpl.java:60)
	at org.seasar.doma.it.auto.AutoFunctionTest.testTwoParams_time(AutoFunctionTest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.seasar.framework.unit.S2TestMethodRunner.executeMethodBody(S2TestMethodRunner.java:678)
	at org.seasar.framework.unit.S2TestMethodRunner.executeMethod(S2TestMethodRunner.java:653)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:618)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:06 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:06 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: 関数 "FUNC_RESULTSET" が見つかりません
Function "FUNC_RESULTSET" not found; SQL statement:
     call func_resultset(?)  [90022-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.command.Parser.readJavaFunction(Parser.java:1919)
	at org.h2.command.Parser.readFunction(Parser.java:1960)
	at org.h2.command.Parser.readTerm(Parser.java:2243)
	at org.h2.command.Parser.readFactor(Parser.java:1850)
	at org.h2.command.Parser.readSum(Parser.java:1837)
	at org.h2.command.Parser.readConcat(Parser.java:1810)
	at org.h2.command.Parser.readCondition(Parser.java:1681)
	at org.h2.command.Parser.readAnd(Parser.java:1661)
	at org.h2.command.Parser.readExpression(Parser.java:1653)
	at org.h2.command.Parser.parserCall(Parser.java:3588)
	at org.h2.command.Parser.parsePrepared(Parser.java:326)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.parse(Parser.java:263)
	at org.h2.command.Parser.prepareCommand(Parser.java:235)
	at org.h2.engine.Session.prepareLocal(Session.java:416)
	at org.h2.engine.Session.prepareCommand(Session.java:377)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1066)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcCallableStatement.<init>(JdbcCallableStatement.java:40)
	at org.h2.jdbc.JdbcConnection.prepareCall(JdbcConnection.java:809)
	at org.seasar.extension.dbcp.impl.ConnectionWrapperImpl.prepareCall(ConnectionWrapperImpl.java:185)
	at org.seasar.doma.it.ItConnection.prepareCall(ItConnection.java:128)
	at org.seasar.doma.internal.jdbc.util.JdbcUtil.prepareCall(JdbcUtil.java:78)
	at org.seasar.doma.internal.jdbc.command.ModuleCommand.execute(ModuleCommand.java:53)
	at org.seasar.doma.it.dao.FunctionDaoImpl.func_resultset(FunctionDaoImpl.java:97)
	at org.seasar.doma.it.auto.AutoFunctionTest.testResultSet(AutoFunctionTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.seasar.framework.unit.S2TestMethodRunner.executeMethodBody(S2TestMethodRunner.java:678)
	at org.seasar.framework.unit.S2TestMethodRunner.executeMethod(S2TestMethodRunner.java:653)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:618)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:06 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:06 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: 関数 "FUNC_RESULTSET_UPDATE" が見つかりません
Function "FUNC_RESULTSET_UPDATE" not found; SQL statement:
     call func_resultset_update(?)  [90022-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.command.Parser.readJavaFunction(Parser.java:1919)
	at org.h2.command.Parser.readFunction(Parser.java:1960)
	at org.h2.command.Parser.readTerm(Parser.java:2243)
	at org.h2.command.Parser.readFactor(Parser.java:1850)
	at org.h2.command.Parser.readSum(Parser.java:1837)
	at org.h2.command.Parser.readConcat(Parser.java:1810)
	at org.h2.command.Parser.readCondition(Parser.java:1681)
	at org.h2.command.Parser.readAnd(Parser.java:1661)
	at org.h2.command.Parser.readExpression(Parser.java:1653)
	at org.h2.command.Parser.parserCall(Parser.java:3588)
	at org.h2.command.Parser.parsePrepared(Parser.java:326)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.parse(Parser.java:263)
	at org.h2.command.Parser.prepareCommand(Parser.java:235)
	at org.h2.engine.Session.prepareLocal(Session.java:416)
	at org.h2.engine.Session.prepareCommand(Session.java:377)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1066)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcCallableStatement.<init>(JdbcCallableStatement.java:40)
	at org.h2.jdbc.JdbcConnection.prepareCall(JdbcConnection.java:809)
	at org.seasar.extension.dbcp.impl.ConnectionWrapperImpl.prepareCall(ConnectionWrapperImpl.java:185)
	at org.seasar.doma.it.ItConnection.prepareCall(ItConnection.java:128)
	at org.seasar.doma.internal.jdbc.util.JdbcUtil.prepareCall(JdbcUtil.java:78)
	at org.seasar.doma.internal.jdbc.command.ModuleCommand.execute(ModuleCommand.java:53)
	at org.seasar.doma.it.dao.FunctionDaoImpl.func_resultset_update(FunctionDaoImpl.java:116)
	at org.seasar.doma.it.auto.AutoFunctionTest.testResultSetAndUpdate(AutoFunctionTest.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.seasar.framework.unit.S2TestMethodRunner.executeMethodBody(S2TestMethodRunner.java:678)
	at org.seasar.framework.unit.S2TestMethodRunner.executeMethod(S2TestMethodRunner.java:653)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:618)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:06 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:06 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: 関数 "FUNC_RESULTSET_UPDATE2" が見つかりません
Function "FUNC_RESULTSET_UPDATE2" not found; SQL statement:
     call func_resultset_update2(?)  [90022-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.command.Parser.readJavaFunction(Parser.java:1919)
	at org.h2.command.Parser.readFunction(Parser.java:1960)
	at org.h2.command.Parser.readTerm(Parser.java:2243)
	at org.h2.command.Parser.readFactor(Parser.java:1850)
	at org.h2.command.Parser.readSum(Parser.java:1837)
	at org.h2.command.Parser.readConcat(Parser.java:1810)
	at org.h2.command.Parser.readCondition(Parser.java:1681)
	at org.h2.command.Parser.readAnd(Parser.java:1661)
	at org.h2.command.Parser.readExpression(Parser.java:1653)
	at org.h2.command.Parser.parserCall(Parser.java:3588)
	at org.h2.command.Parser.parsePrepared(Parser.java:326)
	at org.h2.command.Parser.parse(Parser.java:291)
	at org.h2.command.Parser.parse(Parser.java:263)
	at org.h2.command.Parser.prepareCommand(Parser.java:235)
	at org.h2.engine.Session.prepareLocal(Session.java:416)
	at org.h2.engine.Session.prepareCommand(Session.java:377)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1066)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcCallableStatement.<init>(JdbcCallableStatement.java:40)
	at org.h2.jdbc.JdbcConnection.prepareCall(JdbcConnection.java:809)
	at org.seasar.extension.dbcp.impl.ConnectionWrapperImpl.prepareCall(ConnectionWrapperImpl.java:185)
	at org.seasar.doma.it.ItConnection.prepareCall(ItConnection.java:128)
	at org.seasar.doma.internal.jdbc.util.JdbcUtil.prepareCall(JdbcUtil.java:78)
	at org.seasar.doma.internal.jdbc.command.ModuleCommand.execute(ModuleCommand.java:53)
	at org.seasar.doma.it.dao.FunctionDaoImpl.func_resultset_update2(FunctionDaoImpl.java:135)
	at org.seasar.doma.it.auto.AutoFunctionTest.testResultSetAndUpdate2(AutoFunctionTest.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.seasar.framework.unit.S2TestMethodRunner.executeMethodBody(S2TestMethodRunner.java:678)
	at org.seasar.framework.unit.S2TestMethodRunner.executeMethod(S2TestMethodRunner.java:653)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:618)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:06 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
12-19 12:14:06 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: テーブル "DEPARTMENT" が見つかりません
Table "DEPARTMENT" not found; SQL statement:
update DEPARTMENT set DEPARTMENT_NAME = ? where DEPARTMENT_ID = ? [42102-126]
12-19 12:14:06 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: オブジェクトはすでに閉じられています
The object is already closed [90007-126]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosedForWrite(JdbcConnection.java:1330)
	at org.h2.jdbc.JdbcConnection.rollback(JdbcConnection.java:430)
	at org.seasar.extension.dbcp.impl.DBXAResourceImpl.doRollback(DBXAResourceImpl.java:84)
	at org.seasar.extension.jta.xa.AbstractXAResource.rollback(AbstractXAResource.java:267)
	at org.seasar.extension.dbcp.impl.XAResourceWrapperImpl.rollback(XAResourceWrapperImpl.java:136)
	at org.seasar.extension.jta.XAResourceWrapper.rollback(XAResourceWrapper.java:76)
	at org.seasar.extension.jta.TransactionImpl.rollbackResources(TransactionImpl.java:416)
	at org.seasar.extension.jta.TransactionImpl.rollback(TransactionImpl.java:390)
	at org.seasar.extension.jta.AbstractTransactionManagerImpl.rollback(AbstractTransactionManagerImpl.java:106)
	at org.seasar.framework.unit.S2TestMethodRunner.runTest(S2TestMethodRunner.java:624)
	at org.seasar.framework.unit.S2TestMethodRunner.runMethod(S2TestMethodRunner.java:256)
	at org.seasar.framework.unit.S2TestMethodRunner.run(S2TestMethodRunner.java:172)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.invokeTestMethod(S2TestClassMethodsRunner.java:227)
	at org.seasar.framework.unit.S2TestClassMethodsRunner.run(S2TestClassMethodsRunner.java:89)
	at org.seasar.framework.unit.S2TestClassRunner.run(S2TestClassRunner.java:67)
	at org.seasar.framework.unit.Seasar2.run(Seasar2.java:168)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
